# Generated by Django 5.2 on 2025-04-22 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_options_alter_subject_options_content_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='text',
            options={},
        ),
    ]
